apiVersion: v1
kind: Namespace
metadata:
  name: jupyterhub-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-user-pod-creator
  namespace: jupyterhub-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-user-pod-creator
  namespace: jupyterhub-dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  - pods/attach
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-user-pod-creator-binding
  namespace: jupyterhub-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyterhub-user-pod-creator
subjects:
- kind: ServiceAccount
  name: jupyterhub-user-pod-creator
  namespace: jupyterhub-dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jupyterhub
  name: jupyterhub
  namespace: jupyterhub-dev
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/name: jupyterhub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jupyterhub
  name: jupyterhub
  namespace: jupyterhub-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyterhub
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyterhub
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: jupyterhub-config
        image: ghcr.io/berdatalakehouse/berdl_jupyterhub:pr-1
        name: jupyterhub
        ports:
        - containerPort: 8000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
            drop:
            - ALL
#        volumeMounts:
#        - mountPath: /srv/jupyterhub
#          name: jupyterhub-data
      serviceAccountName: jupyterhub-user-pod-creator
#      volumes:
#      - hostPath:
#          path: /mnt/state/jupyterhub-dev
#          type: Directory
#        name: jupyterhub-data
